In [1]:
# encoding: utf-8
import pandas as pd
import numpy as np
import pickle

In [2]:
with open('afterCleaning/parse_kadai.dump', 'rb') as f:
    kadai = pickle.load(f)

In [3]:
kadai

,projecttype,category,category_niicode,section,section_niicode,startfiscalyear,endfiscalyear,directcost,title_ja,title_en
awardnumber,,,,,,,,,,
4603,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,脳内身体表現の変容機構の理解と制御,Understanding brain plasticity on body represe...
4602,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,動的構造生命科学を拓く新発想測定技術－タンパク質が動作する姿を活写する－,Novel measurement techniques for visualizing '...
4601,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,認知的インタラクションデザイン学：意思疎通のモデル論的理解と人工物設計への応用,Cognitive Interaction Design: A Model-Based Un...
3608,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,脳タンパク質老化と認知症制御,Prevention of brain protein aging and dementia
3607,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,新生鎖の生物学,Nascent-chain Biology
3606,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,ステムセルエイジングから解明する疾患原理,Establishing a new paradigm of the pathogenesi...
3605,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,細胞競合：細胞社会を支える適者生存システム,Cell competition: a mechanism for survival of ...
3604,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,ノンコーディングＲＮＡネオタクソノミ,Neo-taxonomy of noncoding RNAs
3603,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,行動適応を担う脳神経回路の機能シフト機構,Mechanisms underlying the functional shift of ...
3602,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,酸素を基軸とする生命の新たな統合的理解,Oxygen biology: a new criterion for integrated...
3601,area,新学術領域研究(研究領域提案型),73.0,0,0.0,2014.0,2018.0,0.0,細胞死を起点とする生体制御ネットワークの解明,Homeostatic Regulation by Various Types of Cel...
26935006,project,奨励研究,63.0,0,0.0,2014.0,2014.0,600.0,超高精細４Ｋ映像による可視化金型粉砕機を用いたアルファ穀物粉の粉砕挙動の解明,0
26935005,project,奨励研究,63.0,0,0.0,2014.0,2014.0,400.0,小学校における持続可能な社会をめざすための消費者教育の実践事例集作成,0
26935004,project,奨励研究,63.0,0,0.0,2014.0,2014.0,400.0,食の安全とリスクからせまる環境教育プログラムの開発,0
26935003,project,奨励研究,63.0,0,0.0,2014.0,2014.0,600.0,自立と共生から考える高齢社会～高校生が今できること、将来に向けて身につけること,0
26935002,project,奨励研究,63.0,0,0.0,2014.0,2014.0,400.0,幼児期におけるソーシャルスキルを取り入れた養護活動の研究,0
26935001,project,奨励研究,63.0,0,0.0,2014.0,2014.0,600.0,医学と連携した科学教育の礎を築く理科教材開発の研究,0
26934018,project,奨励研究,63.0,0,0.0,2014.0,2014.0,600.0,離島の環境特性を利用した呼吸器疾患と生活環境との影響解明及び疾患改善に向けた研究,0
26934017,project,奨励研究,63.0,0,0.0,2014.0,2014.0,600.0,高齢女性における加齢に伴う筋委縮への新たな治療法の開発を目指した基礎的研究,0
26934016,project,奨励研究,63.0,0,0.0,2014.0,2014.0,400.0,薬科大学女子学生における月経関連症状と生殖的健康について,0
26934015,project,奨励研究,63.0,0,0.0,2014.0,2014.0,300.0,子宮頸がん検診低受診率の解明と子宮頸がん予防対策の効果的な実践方法の検討,0
26934014,project,奨励研究,63.0,0,0.0,2014.0,2015.0,600.0,下半身陽圧負荷装置を用いた歩行運動が下肢痛を有する高齢者の運動機能に及びぼす影響,0
26934013,project,奨励研究,63.0,0,0.0,2014.0,2014.0,500.0,スポーツ競技向上のための特定部分追従動作撮影機構の開発,0
26934012,project,奨励研究,63.0,0,0.0,2014.0,2014.0,600.0,「森の幼稚園」における幼児の体力・運動能力を向上させる要因,0
26934011,project,奨励研究,63.0,0,0.0,2014.0,2014.0,400.0,足部内の力学作用が立位姿勢・バランス保持能力に及ぼす影響,0
26934010,project,奨励研究,63.0,0,0.0,2014.0,2014.0,500.0,体育授業における思考・判断を促すＩＣＴを利用した指導方法に関する実践的研究,0
26934009,project,奨励研究,63.0,0,0.0,2014.0,2014.0,500.0,生徒が主体的に取り組む持久走の授業研究,0
26934008,project,奨励研究,63.0,0,0.0,2014.0,2014.0,300.0,課題を正確にとらえ，「わかる」と「できる」を結びつける，体育学習の実践的研究,0
26934007,project,奨励研究,63.0,0,0.0,2014.0,2014.0,400.0,小学校体育におけるゲームを楽しむ子どもを育てるための授業開発,0
26934006,project,奨励研究,63.0,0,0.0,2014.0,2014.0,300.0,屋外の運動が制限される地域での体力向上を目指した体育授業モデルの開発,0
...,...,...,...,...,...,...,...,...,...,...
18K08452,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,抗菌薬の臨床的ブレイクポイント設定及び検証のためのモデル構築,0
18K08451,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3500.0,感染症診断の新しいアプローチ‐B型肝炎ウイルス感染における爪と毛髪の有用性の検討,0
18K08450,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3300.0,赤血球ATP受容体シグナリングを標的にマラリア感染を防ぐ：耐性のない治療法の確立,0
18K08449,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,劇症型感染における起因菌および外毒素の新規迅速分析法の確立,0
18K08448,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,難治性感染症の再燃と蔓延を阻止する治療戦略の開発とビッグデータ解析,0
18K08447,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,人獣共通病原菌・犬レンサ球菌が保有する定着性・病原性・薬剤耐性機構の解明,0
18K08446,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,PNAを用いたLAMP法によるマクロライド耐性梅毒トレポネーマの検出系の開発,0
18K08445,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3200.0,サフラン色素クロシンを粘膜アジュバントとした経鼻インフルエンザワクチンの開発,0
18K08444,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,新規抗ウイルス自然免疫機構を標的にした抗ウイルス薬スクリーニングシステムの開発,0
18K08443,project,基盤研究(C),72.0,一般,17.0,2018.0,2021.0,3400.0,A群連鎖球菌spy1588遺伝子の酸感受性機構と病原性発症機構の解明,0
18K08442,project,基盤研究(C),72.0,一般,17.0,2018.0,2022.0,3300.0,原発避難区域を含む福島県内全域のダニ媒介性感染症の調査と新たな診断手法の開発,0
18K08441,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3200.0,サイトメガロウイルスの感染細胞指向性をエピジェネティックに型判別する方法の開発,0
18K08440,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,1500.0,プロバイオティクスを用いた放射線性腸管粘膜障害の改善と敗血症発症抑制効果の検討,0
18K08439,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3200.0,RNAiを用いた真菌血症に対する新たな治療戦略,0
18K08438,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,アポリポタンパク質Eの抗ウイルスメカニズムと感染病態機構の解明,0
18K08437,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,次世代シークエンスを活用した高精細ヒトT細胞白血病ウイルス遺伝子発現制御機序解明,0
18K08436,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3300.0,ケモカイン受容体多量体形成阻害機構解明によるHIV感染の病態解明と治療への応用,0
18K08435,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,HIV-1キャプシド構造タンパク質自壊と脱殻の新たな機構解明,0
18K08434,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3500.0,各種アルボウイルスの鑑別診断法の開発,0
18K08433,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,高齢者C型慢性肝炎における抗ウイルス療法完治後の肝癌発症機序の解明,0
18K08432,project,基盤研究(C),72.0,一般,17.0,2018.0,2020.0,3400.0,マクロファージのPerforin-2による殺菌機構の解明,0
22128009,NaN,NaN,73.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22900002,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22900001,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11F01767,NaN,NaN,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11F01514,NaN,NaN,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11F01303,NaN,NaN,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23900002,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23900001,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24900001,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
kadai = kadai[['category_niicode', 'section_niicode','startfiscalyear', 'directcost']]
kadai

             category_niicode  section_niicode  startfiscalyear  directcost
awardnumber
4603                     73.0              0.0           2014.0         0.0
4602                     73.0              0.0           2014.0         0.0
4601                     73.0              0.0           2014.0         0.0
3608                     73.0              0.0           2014.0         0.0
3607                     73.0              0.0           2014.0         0.0
3606                     73.0              0.0           2014.0         0.0
3605                     73.0              0.0           2014.0         0.0
3604                     73.0              0.0           2014.0         0.0
3603                     73.0              0.0           2014.0         0.0
3602                     73.0              0.0           2014.0         0.0
3601                     73.0              0.0           2014.0         0.0
26935006                 63.0              0.0           2014.0       600.0
26935005                 63.0              0.0           2014.0       400.0
26935004                 63.0              0.0           2014.0       400.0
26935003                 63.0              0.0           2014.0       600.0
26935002                 63.0              0.0           2014.0       400.0
26935001                 63.0              0.0           2014.0       600.0
26934018                 63.0              0.0           2014.0       600.0
26934017                 63.0              0.0           2014.0       600.0
26934016                 63.0              0.0           2014.0       400.0
26934015                 63.0              0.0           2014.0       300.0
26934014                 63.0              0.0           2014.0       600.0
26934013                 63.0              0.0           2014.0       500.0
26934012                 63.0              0.0           2014.0       600.0
26934011                 63.0              0.0           2014.0       400.0
26934010                 63.0              0.0           2014.0       500.0
26934009                 63.0              0.0           2014.0       500.0
26934008                 63.0              0.0           2014.0       300.0
26934007                 63.0              0.0           2014.0       400.0
26934006                 63.0              0.0           2014.0       300.0
...                       ...              ...              ...         ...
18K08452                 72.0             17.0           2018.0      3400.0
18K08451                 72.0             17.0           2018.0      3500.0
18K08450                 72.0             17.0           2018.0      3300.0
18K08449                 72.0             17.0           2018.0      3400.0
18K08448                 72.0             17.0           2018.0      3400.0
18K08447                 72.0             17.0           2018.0      3400.0
18K08446                 72.0             17.0           2018.0      3400.0
18K08445                 72.0             17.0           2018.0      3200.0
18K08444                 72.0             17.0           2018.0      3400.0
18K08443                 72.0             17.0           2018.0      3400.0
18K08442                 72.0             17.0           2018.0      3300.0
18K08441                 72.0             17.0           2018.0      3200.0
18K08440                 72.0             17.0           2018.0      1500.0
18K08439                 72.0             17.0           2018.0      3200.0
18K08438                 72.0             17.0           2018.0      3400.0
18K08437                 72.0             17.0           2018.0      3400.0
18K08436                 72.0             17.0           2018.0      3300.0
18K08435                 72.0             17.0           2018.0      3400.0
18K08434                 72.0             17.0           2018.0      3500.0
18K08433                 72.0             17.0           2018.0      3400.0
18K08432                 72.0             17.0           2018.0      3400.0
22128009                 73.0              NaN              NaN         NaN
22900002                 55.0              NaN              NaN         NaN
22900001                 55.0              NaN              NaN         NaN
11F01767                 42.0              NaN              NaN         NaN
11F01514                 42.0              NaN              NaN         NaN
11F01303                 42.0              NaN              NaN         NaN
23900002                 55.0              NaN              NaN         NaN
23900001                 55.0              NaN              NaN         NaN
24900001                 55.0              NaN              NaN         NaN

[146136 rows x 4 columns]

In [5]:
with open('afterCleaning/parse_institution_from_grantlist.dump', 'rb') as f:
    institution = pickle.load(f)

In [6]:
institution

,fiscalyear,grant_sequence,institution_sequence,institution_niicode,institution_mextcode,institution_jspscode,institution
awardnumber,,,,,,,
13J06029,2013,1,1,12613,12613,12613,一橋大学
13J06768,2014,1,1,12611,12611,12611,お茶の水女子大学
13J08587,2013,1,1,14501,14501,14501,神戸大学
13J08700,2013,1,1,34416,34416,34416,関西大学
13J09000,2014,1,1,12601,12601,12601,東京大学
13J40009,2014,1,1,12102,12102,12102,筑波大学
13J40018,2014,1,1,14301,14301,14301,京都大学
13J40059,2014,1,1,12608,12608,12608,東京工業大学
13J40187,2014,1,1,12601,12601,12601,東京大学
14F02732,2014,1,1,12601,12601,12601,東京大学
14F02770,2014,1,1,22604,22604,22604,首都大学東京
14F02786,2014,1,1,14301,14301,14301,京都大学
14F02810,2014,1,1,12601,12601,12601,東京大学
14F02816,2014,1,1,12601,12601,12601,東京大学
14F03086,2014,1,1,15401,15401,15401,広島大学
14F03306,2014,1,1,32641,32641,32641,中央大学
14F03355,2014,1,1,14401,14401,14401,大阪大学
14F03360,2014,1,1,13801,13801,13801,静岡大学
14F03362,2014,1,1,13201,13201,13201,富山大学
14F03381,2014,1,1,63801,63801,63801,国立遺伝学研究所
14F03386,2014,1,1,13901,13901,13901,名古屋大学
14F03391,2014,1,1,13904,13904,13904,豊橋技術科学大学
14F03399,2014,1,1,14403,14403,14403,大阪教育大学
14F03406,2014,1,1,32665,32665,32665,日本大学
14F03511,2014,1,1,182609,82609,82609,公益財団法人東京都医学総合研究所
14F03724,2014,1,1,31302,31302,31302,東北学院大学
14F03764,2014,1,1,13201,13201,13201,富山大学
14F03772,2014,1,1,82706,82706,0,独立行政法人海洋研究開発機構
14F03777,2014,1,1,30109,30109,30109,酪農学園大学
14F03781,2014,1,1,12608,12608,12608,東京工業大学
...,...,...,...,...,...,...,...
3802,2016,1,0,0,0,0,0
3803,2016,1,0,0,0,0,0
3804,2016,1,0,0,0,0,0
3805,2016,1,0,0,0,0,0
3806,2016,1,0,0,0,0,0
3901,2017,1,0,0,0,0,0
3902,2017,1,0,0,0,0,0
3903,2017,1,0,0,0,0,0
3904,2017,1,0,0,0,0,0
3905,2017,1,0,0,0,0,0
4601,2014,1,0,0,0,0,0
4602,2014,1,0,0,0,0,0
4603,2014,1,0,0,0,0,0
4701,2015,1,0,0,0,0,0
4702,2015,1,0,0,0,0,0
4703,2015,1,0,0,0,0,0
4704,2015,1,0,0,0,0,0
4705,2015,1,0,0,0,0,0
4801,2016,1,0,0,0,0,0
4802,2016,1,0,0,0,0,0
4803,2016,1,0,0,0,0,0
4804,2016,1,0,0,0,0,0
4805,2016,1,0,0,0,0,0
4806,2016,1,0,0,0,0,0
4901,2017,1,0,0,0,0,0
4902,2017,1,0,0,0,0,0
4903,2017,1,0,0,0,0,0
4904,2017,1,0,0,0,0,0
4905,2017,1,0,0,0,0,0
4906,2017,1,0,0,0,0,0

In [7]:
institution = institution[['institution_niicode']]
institution

             institution_niicode
awardnumber
13J06029                   12613
13J06768                   12611
13J08587                   14501
13J08700                   34416
13J09000                   12601
13J40009                   12102
13J40018                   14301
13J40059                   12608
13J40187                   12601
14F02732                   12601
14F02770                   22604
14F02786                   14301
14F02810                   12601
14F02816                   12601
14F03086                   15401
14F03306                   32641
14F03355                   14401
14F03360                   13801
14F03362                   13201
14F03381                   63801
14F03386                   13901
14F03391                   13904
14F03399                   14403
14F03406                   32665
14F03511                  182609
14F03724                   31302
14F03764                   13201
14F03772                   82706
14F03777                   30109
14F03781                   12608
...                          ...
3802                           0
3803                           0
3804                           0
3805                           0
3806                           0
3901                           0
3902                           0
3903                           0
3904                           0
3905                           0
4601                           0
4602                           0
4603                           0
4701                           0
4702                           0
4703                           0
4704                           0
4705                           0
4801                           0
4802                           0
4803                           0
4804                           0
4805                           0
4806                           0
4901                           0
4902                           0
4903                           0
4904                           0
4905                           0
4906                           0

[146127 rows x 1 columns]

In [8]:
with open('afterCleaning/parse_member_from_summary.dump', 'rb') as f:
    member = pickle.load(f)

In [9]:
member

,sequence,role,kenkyuusha_id,familyname,givenname
awardnumber,,,,,
15H00001,1,principal_investigator,0,江谷,和樹
15H00002,1,principal_investigator,0,北田,聖子
15H00003,1,principal_investigator,0,多田,英俊
15H00004,1,principal_investigator,0,國本,学史
15H00005,1,principal_investigator,0,北川,美穂
15H00006,1,principal_investigator,0,原口,耕一郎
15H00007,1,principal_investigator,0,森上,優子
15H00008,1,principal_investigator,0,髙木,浩明
15H00009,1,principal_investigator,0,林,圭介
15H00010,1,principal_investigator,0,山本,和雄
15H00011,1,principal_investigator,0,井上,幸
15H00012,1,principal_investigator,0,漆﨑,まり
15H00013,1,principal_investigator,0,張,栄順
15H00014,1,principal_investigator,0,今田,水穂
15H00015,1,principal_investigator,0,長村,祥知
15H00016,1,principal_investigator,0,辻,伸幸
15H00017,1,principal_investigator,0,東野,裕子
15H00018,1,principal_investigator,0,栁,素子
15H00019,1,principal_investigator,0,江口,朗子
15H00020,1,principal_investigator,0,金澤,淳子
15H00021,1,principal_investigator,0,中村,菜穂
15H00022,1,principal_investigator,0,松村,悠子
15H00023,1,principal_investigator,0,柿沼,亮介
15H00024,1,principal_investigator,0,北脇,義友
15H00025,1,principal_investigator,0,栗林,幸雄
15H00026,1,principal_investigator,0,豊田,裕章
15H00027,1,principal_investigator,0,新田,康二
15H00028,1,principal_investigator,0,水村,暁人
15H00029,1,principal_investigator,0,猪熊,樹人
15H00030,1,principal_investigator,0,尾島,志保
...,...,...,...,...,...
3802,1,area_organizer,80300953,榎本,和生
3803,1,area_organizer,80224369,影山,龍一郎
3804,1,area_organizer,60221595,松本,満
3805,1,area_organizer,70135838,河岡,義裕
3806,1,area_organizer,313205,東山,哲也
3901,1,area_organizer,50273850,黒田,真也
3902,1,area_organizer,178089,倉谷,滋
3903,1,area_organizer,80221810,梅田,正明
3904,1,area_organizer,70271020,清水,重臣
3905,1,area_organizer,80303915,立花,誠
4601,1,area_organizer,60262101,植田,一博
4602,1,area_organizer,80186618,神田,大輔
4603,1,area_organizer,50233127,太田,順
4701,1,area_organizer,50128104,宮野,悟
4702,1,area_organizer,80270792,安田,一郎
4703,1,area_organizer,80180553,南部,篤
4704,1,area_organizer,20726260,古川,聡
4705,1,area_organizer,20396162,西田,眞也
4801,1,area_organizer,80322056,笠井,清登
4802,1,area_organizer,220343,大隅,典子
4803,1,area_organizer,80228410,橋本,浩一
4804,1,area_organizer,30322332,武川,睦寛
4805,1,area_organizer,80188846,銅谷,賢治
4806,1,area_organizer,60251055,桜井,武
4901,1,area_organizer,50222427,松島,綱治
4902,1,area_organizer,90431478,川村,賢二
4903,1,area_organizer,30211121,岡ノ谷,一夫
4904,1,area_organizer,20280951,藤田,直也
4905,1,area_organizer,291964,尾藤,晴彦
4906,1,area_organizer,60261161,沈,建仁

In [10]:
member = member[['kenkyuusha_id']]
member

             kenkyuusha_id
awardnumber
15H00001                 0
15H00002                 0
15H00003                 0
15H00004                 0
15H00005                 0
15H00006                 0
15H00007                 0
15H00008                 0
15H00009                 0
15H00010                 0
15H00011                 0
15H00012                 0
15H00013                 0
15H00014                 0
15H00015                 0
15H00016                 0
15H00017                 0
15H00018                 0
15H00019                 0
15H00020                 0
15H00021                 0
15H00022                 0
15H00023                 0
15H00024                 0
15H00025                 0
15H00026                 0
15H00027                 0
15H00028                 0
15H00029                 0
15H00030                 0
...                    ...
3802              80300953
3803              80224369
3804              60221595
3805              70135838
3806                313205
3901              50273850
3902                178089
3903              80221810
3904              70271020
3905              80303915
4601              60262101
4602              80186618
4603              50233127
4701              50128104
4702              80270792
4703              80180553
4704              20726260
4705              20396162
4801              80322056
4802                220343
4803              80228410
4804              30322332
4805              80188846
4806              60251055
4901              50222427
4902              90431478
4903              30211121
4904              20280951
4905                291964
4906              60261161

[133072 rows x 1 columns]

In [11]:
df = kadai.join(institution)
df = df.join(member)
df

,category_niicode,section_niicode,startfiscalyear,directcost,institution_niicode,kenkyuusha_id
awardnumber,,,,,,
4603,73.0,0.0,2014.0,0.0,0.0,50233127.0
4602,73.0,0.0,2014.0,0.0,0.0,80186618.0
4601,73.0,0.0,2014.0,0.0,0.0,60262101.0
3608,73.0,0.0,2014.0,0.0,0.0,20148315.0
3607,73.0,0.0,2014.0,0.0,0.0,40272710.0
3606,73.0,0.0,2014.0,0.0,0.0,70244126.0
3605,73.0,0.0,2014.0,0.0,0.0,50580974.0
3604,73.0,0.0,2014.0,0.0,0.0,30273220.0
3603,73.0,0.0,2014.0,0.0,0.0,90211903.0
3602,73.0,0.0,2014.0,0.0,0.0,80212265.0
3601,73.0,0.0,2014.0,0.0,0.0,294059.0
26935006,63.0,0.0,2014.0,600.0,11501.0,0.0
26935005,63.0,0.0,2014.0,400.0,17501.0,0.0
26935004,63.0,0.0,2014.0,400.0,0.0,0.0
26935003,63.0,0.0,2014.0,600.0,12601.0,0.0
26935002,63.0,0.0,2014.0,400.0,11501.0,0.0
26935001,63.0,0.0,2014.0,600.0,14201.0,0.0
26934018,63.0,0.0,2014.0,600.0,56302.0,0.0
26934017,63.0,0.0,2014.0,600.0,17301.0,0.0
26934016,63.0,0.0,2014.0,400.0,32676.0,0.0
26934015,63.0,0.0,2014.0,300.0,11501.0,0.0
26934014,63.0,0.0,2014.0,600.0,15101.0,0.0
26934013,63.0,0.0,2014.0,500.0,13901.0,0.0
26934012,63.0,0.0,2014.0,600.0,15401.0,0.0
26934011,63.0,0.0,2014.0,400.0,32413.0,0.0
26934010,63.0,0.0,2014.0,500.0,12301.0,0.0
26934009,63.0,0.0,2014.0,500.0,15401.0,0.0
26934008,63.0,0.0,2014.0,300.0,15401.0,0.0
26934007,63.0,0.0,2014.0,400.0,17101.0,0.0
26934006,63.0,0.0,2014.0,300.0,0.0,0.0
...,...,...,...,...,...,...
18K08452,72.0,17.0,2018.0,3400.0,32661.0,90246695.0
18K08451,72.0,17.0,2018.0,3500.0,32661.0,80424711.0
18K08450,72.0,17.0,2018.0,3300.0,32653.0,80328377.0
18K08449,72.0,17.0,2018.0,3400.0,32643.0,80459312.0
18K08448,72.0,17.0,2018.0,3400.0,32620.0,60365591.0
18K08447,72.0,17.0,2018.0,3400.0,32607.0,292855.0
18K08446,72.0,17.0,2018.0,3400.0,32409.0,746993.0
18K08445,72.0,17.0,2018.0,3200.0,31201.0,20372881.0
18K08444,72.0,17.0,2018.0,3400.0,24303.0,10405277.0
18K08443,72.0,17.0,2018.0,3400.0,23903.0,40336673.0
18K08442,72.0,17.0,2018.0,3300.0,21601.0,90277971.0
18K08441,72.0,17.0,2018.0,3200.0,21601.0,50305356.0
18K08440,72.0,17.0,2018.0,1500.0,21601.0,30736690.0
18K08439,72.0,17.0,2018.0,3200.0,17501.0,80301381.0
18K08438,72.0,17.0,2018.0,3400.0,17401.0,60303913.0
18K08437,72.0,17.0,2018.0,3400.0,17401.0,90573105.0
18K08436,72.0,17.0,2018.0,3300.0,17401.0,40628492.0
18K08435,72.0,17.0,2018.0,3400.0,17401.0,30575080.0
18K08434,72.0,17.0,2018.0,3500.0,17301.0,346925.0
18K08433,72.0,17.0,2018.0,3400.0,17102.0,10346786.0
18K08432,72.0,17.0,2018.0,3400.0,17102.0,20325476.0
22128009,73.0,NaN,NaN,NaN,NaN,NaN
22900002,55.0,NaN,NaN,NaN,NaN,NaN
22900001,55.0,NaN,NaN,NaN,NaN,NaN
11F01767,42.0,NaN,NaN,NaN,NaN,NaN
11F01514,42.0,NaN,NaN,NaN,NaN,NaN
11F01303,42.0,NaN,NaN,NaN,NaN,NaN
23900002,55.0,NaN,NaN,NaN,NaN,NaN
23900001,55.0,NaN,NaN,NaN,NaN,NaN
24900001,55.0,NaN,NaN,NaN,NaN,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146136 entries, 4603 to 24900001
Data columns (total 6 columns):
category_niicode       146136 non-null float64
section_niicode        146127 non-null float64
startfiscalyear        146127 non-null float64
directcost             146127 non-null float64
institution_niicode    146127 non-null float64
kenkyuusha_id          133072 non-null float64
dtypes: float64(6)
memory usage: 12.8+ MB

In [13]:
df = df.fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146136 entries, 4603 to 24900001
Data columns (total 6 columns):
category_niicode       146136 non-null float64
section_niicode        146136 non-null float64
startfiscalyear        146136 non-null float64
directcost             146136 non-null float64
institution_niicode    146136 non-null float64
kenkyuusha_id          146136 non-null float64
dtypes: float64(6)
memory usage: 12.8+ MB

In [14]:
df = df.astype({
    'kenkyuusha_id': np.int64
})
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146136 entries, 4603 to 24900001
Data columns (total 6 columns):
category_niicode       146136 non-null float64
section_niicode        146136 non-null float64
startfiscalyear        146136 non-null float64
directcost             146136 non-null float64
institution_niicode    146136 non-null float64
kenkyuusha_id          146136 non-null int64
dtypes: float64(5), int64(1)
memory usage: 7.8+ MB

In [15]:
df

,category_niicode,section_niicode,startfiscalyear,directcost,institution_niicode,kenkyuusha_id
awardnumber,,,,,,
4603,73.0,0.0,2014.0,0.0,0.0,50233127
4602,73.0,0.0,2014.0,0.0,0.0,80186618
4601,73.0,0.0,2014.0,0.0,0.0,60262101
3608,73.0,0.0,2014.0,0.0,0.0,20148315
3607,73.0,0.0,2014.0,0.0,0.0,40272710
3606,73.0,0.0,2014.0,0.0,0.0,70244126
3605,73.0,0.0,2014.0,0.0,0.0,50580974
3604,73.0,0.0,2014.0,0.0,0.0,30273220
3603,73.0,0.0,2014.0,0.0,0.0,90211903
3602,73.0,0.0,2014.0,0.0,0.0,80212265
3601,73.0,0.0,2014.0,0.0,0.0,294059
26935006,63.0,0.0,2014.0,600.0,11501.0,0
26935005,63.0,0.0,2014.0,400.0,17501.0,0
26935004,63.0,0.0,2014.0,400.0,0.0,0
26935003,63.0,0.0,2014.0,600.0,12601.0,0
26935002,63.0,0.0,2014.0,400.0,11501.0,0
26935001,63.0,0.0,2014.0,600.0,14201.0,0
26934018,63.0,0.0,2014.0,600.0,56302.0,0
26934017,63.0,0.0,2014.0,600.0,17301.0,0
26934016,63.0,0.0,2014.0,400.0,32676.0,0
26934015,63.0,0.0,2014.0,300.0,11501.0,0
26934014,63.0,0.0,2014.0,600.0,15101.0,0
26934013,63.0,0.0,2014.0,500.0,13901.0,0
26934012,63.0,0.0,2014.0,600.0,15401.0,0
26934011,63.0,0.0,2014.0,400.0,32413.0,0
26934010,63.0,0.0,2014.0,500.0,12301.0,0
26934009,63.0,0.0,2014.0,500.0,15401.0,0
26934008,63.0,0.0,2014.0,300.0,15401.0,0
26934007,63.0,0.0,2014.0,400.0,17101.0,0
26934006,63.0,0.0,2014.0,300.0,0.0,0
...,...,...,...,...,...,...
18K08452,72.0,17.0,2018.0,3400.0,32661.0,90246695
18K08451,72.0,17.0,2018.0,3500.0,32661.0,80424711
18K08450,72.0,17.0,2018.0,3300.0,32653.0,80328377
18K08449,72.0,17.0,2018.0,3400.0,32643.0,80459312
18K08448,72.0,17.0,2018.0,3400.0,32620.0,60365591
18K08447,72.0,17.0,2018.0,3400.0,32607.0,292855
18K08446,72.0,17.0,2018.0,3400.0,32409.0,746993
18K08445,72.0,17.0,2018.0,3200.0,31201.0,20372881
18K08444,72.0,17.0,2018.0,3400.0,24303.0,10405277
18K08443,72.0,17.0,2018.0,3400.0,23903.0,40336673
18K08442,72.0,17.0,2018.0,3300.0,21601.0,90277971
18K08441,72.0,17.0,2018.0,3200.0,21601.0,50305356
18K08440,72.0,17.0,2018.0,1500.0,21601.0,30736690
18K08439,72.0,17.0,2018.0,3200.0,17501.0,80301381
18K08438,72.0,17.0,2018.0,3400.0,17401.0,60303913
18K08437,72.0,17.0,2018.0,3400.0,17401.0,90573105
18K08436,72.0,17.0,2018.0,3300.0,17401.0,40628492
18K08435,72.0,17.0,2018.0,3400.0,17401.0,30575080
18K08434,72.0,17.0,2018.0,3500.0,17301.0,346925
18K08433,72.0,17.0,2018.0,3400.0,17102.0,10346786
18K08432,72.0,17.0,2018.0,3400.0,17102.0,20325476
22128009,73.0,0.0,0.0,0.0,0.0,0
22900002,55.0,0.0,0.0,0.0,0.0,0
22900001,55.0,0.0,0.0,0.0,0.0,0
11F01767,42.0,0.0,0.0,0.0,0.0,0
11F01514,42.0,0.0,0.0,0.0,0.0,0
11F01303,42.0,0.0,0.0,0.0,0.0,0
23900002,55.0,0.0,0.0,0.0,0.0,0
23900001,55.0,0.0,0.0,0.0,0.0,0
24900001,55.0,0.0,0.0,0.0,0.0,0

In [16]:
import configparser

config = configparser.ConfigParser()
config.read('config.ini')
username = config['mariadb']['username']
password = config['mariadb']['password']
database = config['mariadb']['database']
url = 'mysql+pymysql://' + username + ':' + password + '@localhost:3306/' + database + '?charset=utf8'

In [17]:
from sqlalchemy import create_engine
from sqlalchemy.types import String, Integer

engine = create_engine(url, echo=True)

df.to_sql('grantaward', engine, if_exists='replace',
          dtype={
              'awardnumber': String(256),
              'category_niicode': Integer,
              'section': String(256),
              'startfiscalyear': Integer,
              'directcost': Integer,
              'niicode': Integer,
              'kenkyuusha_id': Integer,                 
                })

2018-06-17 11:09:13,768 INFO sqlalchemy.engine.base.Engine SHOW VARIABLES LIKE 'sql_mode'
2018-06-17 11:09:13,783 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,783 INFO sqlalchemy.engine.base.Engine SELECT DATABASE()
2018-06-17 11:09:13,783 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,783 INFO sqlalchemy.engine.base.Engine show collation where `Charset` = 'utf8' and `Collation` = 'utf8_bin'
2018-06-17 11:09:13,783 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,799 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
2018-06-17 11:09:13,799 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,799 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
2018-06-17 11:09:13,799 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,799 INFO sqlalchemy.engine.base.Engine SELECT CAST('test collated returns' AS CHAR CHARACTER SET utf8) COLLATE utf8_bin AS anon_1
2018-06-17 11:09:13,799 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,799 INFO sqlalchemy.engine.base.Engine DESCRIBE `grantaward`
2018-06-17 11:09:13,814 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,814 INFO sqlalchemy.engine.base.Engine ROLLBACK
2018-06-17 11:09:13,814 INFO sqlalchemy.engine.base.Engine
CREATE TABLE grantaward (
	awardnumber VARCHAR(256),
	category_niicode INTEGER,
	section_niicode FLOAT(53),
	startfiscalyear INTEGER,
	directcost INTEGER,
	institution_niicode FLOAT(53),
	kenkyuusha_id INTEGER
)


2018-06-17 11:09:13,814 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,861 INFO sqlalchemy.engine.base.Engine COMMIT
2018-06-17 11:09:13,861 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_grantaward_awardnumber ON grantaward (awardnumber)
2018-06-17 11:09:13,861 INFO sqlalchemy.engine.base.Engine {}
2018-06-17 11:09:13,893 INFO sqlalchemy.engine.base.Engine COMMIT
2018-06-17 11:09:13,986 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2018-06-17 11:09:15,841 INFO sqlalchemy.engine.base.Engine INSERT INTO grantaward (awardnumber, category_niicode, section_niicode, startfiscalyear, directcost, institution_niicode, kenkyuusha_id) VALUES (%(awardnumber)s, %(category_niicode)s, %(section_niicode)s, %(startfiscalyear)s, %(directcost)s, %(institution_niicode)s, %(kenkyuusha_id)s)
2018-06-17 11:09:15,841 INFO sqlalchemy.engine.base.Engine ({'awardnumber': '4603', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 50233127}, {'awardnumber': '4602', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 80186618}, {'awardnumber': '4601', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 60262101}, {'awardnumber': '3608', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 20148315}, {'awardnumber': '3607', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 40272710}, {'awardnumber': '3606', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 70244126}, {'awardnumber': '3605', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 50580974}, {'awardnumber': '3604', 'category_niicode': 73.0, 'section_niicode': 0.0, 'startfiscalyear': 2014.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 30273220}  ... displaying 10 of 146136 total bound parameter sets ...  {'awardnumber': '23900001', 'category_niicode': 55.0, 'section_niicode': 0.0, 'startfiscalyear': 0.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 0}, {'awardnumber': '24900001', 'category_niicode': 55.0, 'section_niicode': 0.0, 'startfiscalyear': 0.0, 'directcost': 0.0, 'institution_niicode': 0.0, 'kenkyuusha_id': 0})
2018-06-17 11:09:23,784 INFO sqlalchemy.engine.base.Engine COMMIT